name: James Hennessy
markdown: kramdown
highlighter: rouge
highlight_theme: github  # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  math_engine: katex
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-katex
  - jekyll-twitter-plugin
  - jemoji
  # - bootstrap
  # - material-sass
collections:
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

enable_google_analytics:  false
enable_mansory:           true
enable_math:              true
enable_tooltips:          false
enable_darkmode:          false
show_social_icons:        false

social_media:
  behance: your_username
  dribbble: your_username  
  facebook: your_username
  hackerrank: your_username
  instagram: your_username
  keybase: your_username
  linkedin: jameshennessy1
  medium: your_username
  stackoverflow: your_user_id
  telegram: your_username
  twitter: your_username
  unsplash: your_username
  vk: your_username
  website: http://your_website_url
  youtube: your_username
